# Generated by Django 5.1.2 on 2024-11-09 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_categories_options_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
    ]
