# Generated by Django 5.1.2 on 2024-11-09 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_news_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='description',
        ),
    ]
