# Generated by Django 5.1.2 on 2024-11-09 12:17

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_news_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='description',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
